[package]
name = "spark-script"
description = "Scripting: Luau bindings and hot reload."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
spark-core.workspace = true
mlua.workspace = true
log.workspace = true
serde_json = "1"

[dev-dependencies]
spark-physics.workspace = true
